# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

host:                0.0.0.0

# Setup
title:               BLOG
tagline:             "拣尽寒枝不肯栖，寂寞沙洲冷。"
description:         "陈卡卡个人博客"
url:                 http://kaka.xy-kaka.cn/
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              kakachan
  url:               https://github.com/chen-kaka
  email:             chen-kaka@163.com

# Custom vars
version:             1.0.0

# Gems
gems:                [jekyll-paginate]
